Name:           ros-melodic-flexbe-onboard
Version:        1.2.1
Release:        1%{?dist}
Summary:        ROS flexbe_onboard package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/flexbe_onboard
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-flexbe-core
Requires:       ros-melodic-flexbe-msgs
Requires:       ros-melodic-rospy
Requires:       ros-melodic-smach-ros
BuildRequires:  ros-melodic-catkin

%description
flexbe_onboard implements the robot-side of the behavior engine from where all
behaviors are started.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sun Jun 02 2019 Philipp Schillinger <schillin@kth.se> - 1.2.1-1
- Autogenerated by Bloom

* Tue Apr 09 2019 Philipp Schillinger <schillin@kth.se> - 1.1.2-0
- Autogenerated by Bloom

* Tue Dec 18 2018 Philipp Schillinger <schillin@kth.se> - 1.1.1-0
- Autogenerated by Bloom

